/* AS ADMIN, GRANT THE NEEDED RIGHTS TO STAGING */

GRANT DWROLE, OML_DEVELOPER, CREATE TABLE, CREATE VIEW TO STAGING;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO STAGING;
GRANT EXECUTE ON DBMS_CLOUD TO STAGING;
ALTER USER STAGING QUOTA UNLIMITED ON DATA;
