CREATE TABLE ASSIGNMENT_SUBMISSIONS (
"SOURCESYSTEM" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"AUTHORIZEDUSERS" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ASSIGNID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ASSIGNNAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ASSIGNMAXGRADE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"USERHASH" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ASSIGNGRADE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ATTEMPTNUMBER" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"LATEST" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"SUBMISSION" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ONLINETEXT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"USERINFODATA" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP"
);
