CREATE TABLE QUESTION_ANSWERS_VERSIONS (
"SOURCESYSTEM" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"AUTHORIZEDUSERS" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONPARENT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONNAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONTEXT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONTEXTFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"GENERALFEEDBACK" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"GENERALFEEDBACKFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"DEFAULTMARK" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"PENALTY" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QTYPE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"LENGTH" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONSTAMP" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNTIMECREATED" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNTIMECREATEDSTRING" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNTIMEMODIFIED" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNTIMEMODIFIEDSTRING" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNCREATEDBY" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QNMODIFIEDBY" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONANSWERSID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ANSWER" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ANSWERFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FRACTION" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACK" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACKFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONVERSIONID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONBANKENTRYID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"VERSION" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"STATUS" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONBANKENTRYIDNUMBER" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"OWNERID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONREFERENCESID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"USINGCONTEXTID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"COMPONENT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONAREA" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"ITEMID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONREFERENCESVERSION" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORIESID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYNAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYCONTEXTID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"INFO" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"INFOFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYSTAMP" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYPARENT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"SORTORDER" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONCATEGORYIDNUMBER" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"SLOT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"EFFECTIVEWEIGHT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"DISCRIMINATIONINDEX" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"DISCRIMINATIVEEFFICIENCY" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"SD" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FACILITY" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"RANDOMGUESSSCORE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QBEUSERNAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"CONTEXTID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"PATH" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONATTEMPTSID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QATIMEMODIFIED" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QATIMEMODIFIEDSTRING" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QASTEPID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QASTEPCREATED" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QASTEPCREATEDSTRING" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONATTEMPTSTEPDATANAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUESTIONATTEMPTSTEPDATAVALUE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUIZATTEMPTSID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUIZATTEMPTSUNIQUEID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUIZID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUIZNAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QUIZGRADE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACKTEXT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACKTEXTFORMAT" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACKMINGRADE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"FEEDBACKMAXGRADE" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"COURSEID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"COURSEMODULESID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"MODULENAME" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"QZATUSERID" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP",
"USERINFODATA" VARCHAR2(32672 BYTE) COLLATE "USING_NLS_COMP"
);


-- Enable the REST service on the table.
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'STAGING',
                       p_object => 'QUESTION_ANSWERS_VERSIONS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'raw',
                       p_auto_rest_auth => TRUE);

    commit;

END;

-- Create a REST Data Service Module.
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'REST_FOR_MOODLE',
      p_base_path      => 'moodle/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => '');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'REST_FOR_MOODLE',
      p_pattern        => 'raw/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => '');

  COMMIT; 
END;

-- Building the Post handler stored procedure.
CREATE OR REPLACE PROCEDURE INS_Q_A_V (
  p_sourcesystem IN question_answers_versions.sourcesystem%TYPE,
)
AS
BEGIN
  INSERT INTO question_answers_versions (sourcesystem)
  VALUES (p_sourcesystem);
EXCEPTION
  WHEN OTHERS THEN
    HTP.print(SQLERRM);
END;
/

-- Web service POST handler calling the stored procedure.
BEGIN
INS_Q_A_V(
	p_sourcesystem => :p_sourcesystem
);
END;
-- The URL to call ends with /ords/staging/moodle/raw/

--If needed, drop the QUESTION_ANSWERS_VERSIONS table.
DROP TABLE STAGING.QUESTION_ANSWERS_VERSIONS;
--If needed, drop the QUESTION_ANSWERS_VERSIONS procedure.
DROP PROCEDURE INS_Q_A_V;
